
INSERT INTO public.schemes (slug, name_en, name_hi, short_description_en, short_description_hi, details_en, details_hi, category, ministry_en, ministry_hi, benefits_en, benefits_hi, min_age, max_age, max_income, allowed_states, occupations, education_levels, gender, area_type, other_conditions, application_steps_en, application_steps_hi, official_source_url, official_application_url, source_name, last_verified, url_status) VALUES

('pm-kisan', 'PM-KISAN', 'पीएम-किसान',
'Income support for land-holding farmer families.',
'ज़मीन रखने वाले किसान परिवारों को आर्थिक मदद।',
'PM-KISAN is a central sector scheme that provides income support to land-holding farmer families across India. The amount is paid directly into the beneficiary''s bank account in three equal instalments during the year.',
'पीएम-किसान एक केंद्रीय योजना है जिसमें ज़मीन रखने वाले किसान परिवारों को आर्थिक सहायता दी जाती है। पैसा साल में तीन बराबर किस्तों में सीधे बैंक खाते में आता है।',
'agriculture', 'Ministry of Agriculture and Farmers Welfare', 'कृषि एवं किसान कल्याण मंत्रालय',
ARRAY['Financial support paid in three instalments each year','Money is transferred directly to the bank account','Aadhaar-linked direct benefit transfer'],
ARRAY['हर साल तीन किस्तों में आर्थिक सहायता','पैसा सीधे बैंक खाते में','आधार से जुड़ा सीधा भुगतान'],
18, NULL, NULL, '{}', ARRAY['farmer'], '{}', NULL, NULL,
'[{"key":"land","en":"The family must own cultivable land recorded in its name in the land records.","hi":"परिवार के नाम पर खेती योग्य ज़मीन का रिकॉर्ड होना चाहिए।"},{"key":"exclusion","en":"Income tax payers, institutional land holders and certain government employees/professionals are excluded.","hi":"आयकर देने वाले, संस्थागत भूमि धारक और कुछ सरकारी कर्मचारी/पेशेवर इस योजना से बाहर हैं।"}]'::jsonb,
ARRAY['Open the official PM-KISAN portal.','Go to the Farmers Corner and choose New Farmer Registration.','Enter your Aadhaar number, state and land details.','Submit the form and note your registration number.','Check your status later on the same portal.'],
ARRAY['आधिकारिक पीएम-किसान पोर्टल खोलें।','Farmers Corner में जाकर New Farmer Registration चुनें।','आधार नंबर, राज्य और ज़मीन की जानकारी भरें।','फ़ॉर्म जमा करें और रजिस्ट्रेशन नंबर लिख लें।','बाद में उसी पोर्टल पर स्थिति देखें।'],
'https://pmkisan.gov.in/', 'https://pmkisan.gov.in/', 'Government of India', '2026-09-12', 'verified'),

('ayushman-bharat-pmjay', 'Ayushman Bharat PM-JAY', 'आयुष्मान भारत पीएम-जय',
'Health cover for hospital treatment for eligible families.',
'पात्र परिवारों को अस्पताल में इलाज के लिए स्वास्थ्य कवर।',
'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana provides health cover for secondary and tertiary hospital care to eligible families at empanelled public and private hospitals. Eligibility is based on the deprivation and occupational criteria of the Socio-Economic Caste Census, and on certain state-notified lists.',
'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना पात्र परिवारों को सूचीबद्ध सरकारी और निजी अस्पतालों में इलाज का कवर देती है। पात्रता सामाजिक-आर्थिक जाति जनगणना के मानकों और कुछ राज्य सूचियों पर आधारित है।',
'health', 'National Health Authority, Ministry of Health and Family Welfare', 'राष्ट्रीय स्वास्थ्य प्राधिकरण, स्वास्थ्य एवं परिवार कल्याण मंत्रालय',
ARRAY['Cashless hospital treatment at empanelled hospitals','Cover for the whole eligible family','No restriction on family size or age for eligible households'],
ARRAY['सूचीबद्ध अस्पतालों में कैशलेस इलाज','पूरे पात्र परिवार के लिए कवर','पात्र परिवारों के लिए सदस्य संख्या या उम्र की कोई सीमा नहीं'],
NULL, NULL, NULL, '{}', '{}', '{}', NULL, NULL,
'[{"key":"secc","en":"The household must appear in the eligible list based on Socio-Economic Caste Census deprivation/occupational criteria or a state-notified list.","hi":"परिवार का नाम सामाजिक-आर्थिक जाति जनगणना के मानकों या राज्य की अधिसूचित सूची में होना चाहिए।"},{"key":"verification","en":"Eligibility must be confirmed on the official beneficiary portal or at a Common Service Centre.","hi":"पात्रता की पुष्टि आधिकारिक पोर्टल या कॉमन सर्विस सेंटर पर करानी होगी।"}]'::jsonb,
ARRAY['Open the official PM-JAY website.','Use the beneficiary search to check if your family is listed.','Visit an empanelled hospital or a Common Service Centre with your Aadhaar and ration card.','Complete verification to get your Ayushman card.'],
ARRAY['आधिकारिक पीएम-जय वेबसाइट खोलें।','लाभार्थी खोज में देखें कि आपका परिवार सूची में है या नहीं।','आधार और राशन कार्ड लेकर सूचीबद्ध अस्पताल या कॉमन सर्विस सेंटर जाएँ।','सत्यापन पूरा करके आयुष्मान कार्ड लें।'],
'https://pmjay.gov.in/', NULL, 'National Health Authority', '2026-09-12', 'source_only'),

('central-sector-scholarship', 'Central Sector Scheme of Scholarships for College and University Students', 'कॉलेज एवं विश्वविद्यालय छात्रों के लिए केंद्रीय क्षेत्र छात्रवृत्ति योजना',
'Scholarship for meritorious students from lower-income families.',
'कम आय वाले परिवारों के मेधावी छात्रों के लिए छात्रवृत्ति।',
'This scholarship supports students who scored above the cut-off in their Class 12 board examination and are pursuing regular degree courses. Applications are made through the National Scholarship Portal and must be renewed each year.',
'यह छात्रवृत्ति उन छात्रों के लिए है जिन्होंने कक्षा 12 बोर्ड परीक्षा में निर्धारित कट-ऑफ से ऊपर अंक पाए हैं और नियमित डिग्री कोर्स कर रहे हैं। आवेदन नेशनल स्कॉलरशिप पोर्टल से होता है और हर साल नवीनीकरण ज़रूरी है।',
'education', 'Ministry of Education, Department of Higher Education', 'शिक्षा मंत्रालय, उच्च शिक्षा विभाग',
ARRAY['Annual scholarship amount paid into the student''s bank account','Renewable for the duration of the course subject to conditions','Applied for online through the National Scholarship Portal'],
ARRAY['छात्र के बैंक खाते में हर साल छात्रवृत्ति राशि','शर्तों के अनुसार कोर्स की अवधि तक नवीनीकरण','नेशनल स्कॉलरशिप पोर्टल से ऑनलाइन आवेदन'],
17, 30, 450000, '{}', ARRAY['student'], ARRAY['class-12','undergraduate','postgraduate'], NULL, NULL,
'[{"key":"marks","en":"You must be above the prescribed percentile cut-off of your Class 12 board examination.","hi":"आपके कक्षा 12 बोर्ड के अंक निर्धारित पर्सेंटाइल कट-ऑफ से ऊपर होने चाहिए।"},{"key":"course","en":"You must be enrolled in a regular degree course, not a distance or correspondence course.","hi":"आपको नियमित डिग्री कोर्स में पढ़ना चाहिए, दूरस्थ शिक्षा में नहीं।"},{"key":"no-other","en":"You should not be receiving another central scholarship for the same purpose.","hi":"आप इसी उद्देश्य के लिए कोई दूसरी केंद्रीय छात्रवृत्ति नहीं ले रहे हों।"}]'::jsonb,
ARRAY['Open the National Scholarship Portal.','Register with your Aadhaar or enrolment details and create a One Time Registration.','Select this scholarship and fill the application form.','Upload your Class 12 marksheet, income certificate and bank details.','Submit and note your application number for tracking.'],
ARRAY['नेशनल स्कॉलरशिप पोर्टल खोलें।','आधार या नामांकन जानकारी से रजिस्टर करें और One Time Registration बनाएँ।','यह छात्रवृत्ति चुनें और आवेदन फ़ॉर्म भरें।','कक्षा 12 की मार्कशीट, आय प्रमाण पत्र और बैंक जानकारी अपलोड करें।','फ़ॉर्म जमा करें और आवेदन नंबर सुरक्षित रखें।'],
'https://scholarships.gov.in/', 'https://scholarships.gov.in/', 'Ministry of Education', '2026-09-12', 'verified'),

('pm-svanidhi', 'PM SVANidhi', 'पीएम स्वनिधि',
'Working capital loan for street vendors.',
'रेहड़ी-पटरी विक्रेताओं के लिए कार्यशील पूँजी ऋण।',
'PM Street Vendor''s AtmaNirbhar Nidhi provides collateral-free working capital loans to street vendors, with interest subsidy on timely repayment and higher loan amounts on successful repayment of earlier loans.',
'पीएम स्ट्रीट वेंडर आत्मनिर्भर निधि रेहड़ी-पटरी विक्रेताओं को बिना गारंटी कार्यशील पूँजी ऋण देती है। समय पर भुगतान पर ब्याज सब्सिडी और अगली बार ज़्यादा ऋण मिलता है।',
'employment', 'Ministry of Housing and Urban Affairs', 'आवास एवं शहरी कार्य मंत्रालय',
ARRAY['Collateral-free working capital loan','Interest subsidy on timely repayment','Higher loan amount on repayment of the earlier loan','Incentive for digital transactions'],
ARRAY['बिना गारंटी कार्यशील पूँजी ऋण','समय पर भुगतान पर ब्याज सब्सिडी','पहला ऋण चुकाने पर अधिक राशि','डिजिटल लेनदेन पर प्रोत्साहन'],
18, NULL, NULL, '{}', ARRAY['street-vendor','self-employed'], '{}', NULL, 'urban',
'[{"key":"vending","en":"You must be a street vendor in an urban area with a certificate of vending, identity card or a letter of recommendation from the urban local body.","hi":"आप शहरी क्षेत्र में रेहड़ी-पटरी विक्रेता हों और आपके पास वेंडिंग सर्टिफिकेट, पहचान पत्र या शहरी निकाय की सिफ़ारिश चिट्ठी हो।"}]'::jsonb,
ARRAY['Open the official PM SVANidhi portal.','Apply as a vendor using your mobile number linked to Aadhaar.','Fill the loan application and select your lending institution.','Submit your vending certificate or letter of recommendation.','Track your loan application status on the portal.'],
ARRAY['आधिकारिक पीएम स्वनिधि पोर्टल खोलें।','आधार से जुड़े मोबाइल नंबर से वेंडर के रूप में आवेदन करें।','ऋण आवेदन भरें और ऋण देने वाली संस्था चुनें।','वेंडिंग सर्टिफिकेट या सिफ़ारिश पत्र जमा करें।','पोर्टल पर आवेदन की स्थिति देखें।'],
'https://pmsvanidhi.mohua.gov.in/', 'https://pmsvanidhi.mohua.gov.in/', 'Ministry of Housing and Urban Affairs', '2026-09-12', 'verified'),

('pmuy', 'Pradhan Mantri Ujjwala Yojana', 'प्रधानमंत्री उज्ज्वला योजना',
'LPG connection for women from eligible households.',
'पात्र परिवारों की महिलाओं को एलपीजी कनेक्शन।',
'Pradhan Mantri Ujjwala Yojana provides a deposit-free LPG connection to adult women of eligible households, along with support for the first refill and stove as notified.',
'प्रधानमंत्री उज्ज्वला योजना पात्र परिवारों की वयस्क महिलाओं को जमा-मुक्त एलपीजी कनेक्शन देती है, साथ में अधिसूचित शर्तों के अनुसार पहली रिफिल और चूल्हे की सहायता।',
'women-child', 'Ministry of Petroleum and Natural Gas', 'पेट्रोलियम एवं प्राकृतिक गैस मंत्रालय',
ARRAY['Deposit-free LPG connection in the woman''s name','Support for first refill and stove as notified','Cleaner cooking fuel for the household'],
ARRAY['महिला के नाम पर जमा-मुक्त एलपीजी कनेक्शन','अधिसूचित शर्तों के अनुसार पहली रिफिल और चूल्हा सहायता','घर के लिए साफ़ ईंधन'],
18, NULL, NULL, '{}', '{}', '{}', 'female', NULL,
'[{"key":"household","en":"The household must belong to one of the eligible categories notified under the scheme and must not already have an LPG connection.","hi":"परिवार योजना में अधिसूचित पात्र श्रेणियों में से किसी एक में आए और उसके पास पहले से एलपीजी कनेक्शन न हो।"},{"key":"declaration","en":"A self-declaration in the prescribed format is required.","hi":"निर्धारित प्रारूप में स्व-घोषणा देनी होगी।"}]'::jsonb,
ARRAY['Open the official Ujjwala website.','Choose your preferred LPG distributor company.','Fill the Ujjwala application form online or at the distributor.','Submit your Aadhaar, address proof and bank details.','Collect your connection from the distributor.'],
ARRAY['आधिकारिक उज्ज्वला वेबसाइट खोलें।','अपनी पसंद की एलपीजी कंपनी चुनें।','उज्ज्वला आवेदन फ़ॉर्म ऑनलाइन या वितरक के पास भरें।','आधार, पते का प्रमाण और बैंक जानकारी जमा करें।','वितरक से कनेक्शन प्राप्त करें।'],
'https://www.pmuy.gov.in/', 'https://www.pmuy.gov.in/', 'Ministry of Petroleum and Natural Gas', '2026-09-12', 'verified'),

('sukanya-samriddhi', 'Sukanya Samriddhi Account', 'सुकन्या समृद्धि खाता',
'Small savings account for a girl child.',
'बालिका के लिए छोटी बचत योजना।',
'Sukanya Samriddhi Account is a small savings scheme for a girl child below the age of ten years. The account is opened by a guardian at a post office or authorised bank and earns interest at the rate notified by the Government of India.',
'सुकन्या समृद्धि खाता दस साल से कम उम्र की बालिका के लिए छोटी बचत योजना है। खाता अभिभावक द्वारा डाकघर या अधिकृत बैंक में खोला जाता है और भारत सरकार द्वारा अधिसूचित दर पर ब्याज मिलता है।',
'women-child', 'Ministry of Finance, National Savings Institute', 'वित्त मंत्रालय, राष्ट्रीय बचत संस्थान',
ARRAY['Interest at the rate notified by the Government of India','Deposits qualify for tax benefit under the Income Tax Act','Partial withdrawal allowed for higher education as per rules'],
ARRAY['भारत सरकार द्वारा अधिसूचित दर पर ब्याज','आयकर अधिनियम के तहत कर लाभ','नियमों के अनुसार उच्च शिक्षा के लिए आंशिक निकासी'],
NULL, 10, NULL, '{}', '{}', '{}', 'female', NULL,
'[{"key":"guardian","en":"The account is opened and operated by a guardian until the girl turns 18.","hi":"खाता 18 वर्ष की उम्र तक अभिभावक द्वारा चलाया जाता है।"},{"key":"limit","en":"Not more than two accounts per family are allowed, except in notified cases of twins or triplets.","hi":"एक परिवार में दो से अधिक खाते नहीं, जुड़वाँ या तीन बच्चों के अधिसूचित मामलों को छोड़कर।"},{"key":"offline","en":"The account is opened in person at a post office or authorised bank branch.","hi":"खाता डाकघर या अधिकृत बैंक शाखा में जाकर खोला जाता है।"}]'::jsonb,
ARRAY['Read the scheme rules on the official National Savings Institute website.','Collect the account opening form from a post office or authorised bank.','Fill the form and attach the girl child''s birth certificate and guardian''s KYC documents.','Make the first deposit and collect the passbook.'],
ARRAY['राष्ट्रीय बचत संस्थान की आधिकारिक वेबसाइट पर नियम पढ़ें।','डाकघर या अधिकृत बैंक से खाता खोलने का फ़ॉर्म लें।','फ़ॉर्म भरें और बालिका का जन्म प्रमाण पत्र व अभिभावक के केवाईसी दस्तावेज़ लगाएँ।','पहली जमा राशि दें और पासबुक लें।'],
'https://www.nsiindia.gov.in/', NULL, 'National Savings Institute', '2026-09-12', 'source_only'),

('pmay-gramin', 'Pradhan Mantri Awaas Yojana - Gramin', 'प्रधानमंत्री आवास योजना - ग्रामीण',
'Assistance to build a pucca house in rural areas.',
'ग्रामीण क्षेत्रों में पक्का घर बनाने के लिए सहायता।',
'PMAY-Gramin provides assistance to eligible rural households without a pucca house to build one, with support for a toilet and for wages under MGNREGS as per scheme rules. Beneficiaries are identified from notified survey lists.',
'पीएमएवाई-ग्रामीण उन पात्र ग्रामीण परिवारों को पक्का घर बनाने में मदद करती है जिनके पास पक्का घर नहीं है। नियमों के अनुसार शौचालय और मनरेगा मज़दूरी की सहायता भी मिलती है। लाभार्थी अधिसूचित सर्वे सूची से चुने जाते हैं।',
'housing', 'Ministry of Rural Development', 'ग्रामीण विकास मंत्रालय',
ARRAY['Financial assistance in instalments to build a pucca house','Additional support for a toilet as per scheme rules','Assistance linked with other rural schemes as notified'],
ARRAY['पक्का घर बनाने के लिए किस्तों में आर्थिक सहायता','नियमों के अनुसार शौचालय के लिए अतिरिक्त सहायता','अन्य ग्रामीण योजनाओं से जुड़ी सहायता'],
18, NULL, NULL, '{}', '{}', '{}', NULL, 'rural',
'[{"key":"no-pucca","en":"The household must not already own a pucca house.","hi":"परिवार के पास पहले से पक्का घर नहीं होना चाहिए।"},{"key":"list","en":"The household must appear in the notified beneficiary or survey list verified by the Gram Panchayat.","hi":"परिवार का नाम ग्राम पंचायत द्वारा सत्यापित अधिसूचित लाभार्थी या सर्वे सूची में होना चाहिए।"}]'::jsonb,
ARRAY['Open the official PMAY-Gramin portal to read the scheme rules.','Check whether your household appears in the beneficiary list.','Contact your Gram Panchayat or Block office for survey and verification.','Provide your Aadhaar, bank account and job card details.','Track sanction and instalments on the portal.'],
ARRAY['नियम पढ़ने के लिए आधिकारिक पीएमएवाई-ग्रामीण पोर्टल खोलें।','देखें कि आपका परिवार लाभार्थी सूची में है या नहीं।','सर्वे और सत्यापन के लिए ग्राम पंचायत या ब्लॉक कार्यालय से संपर्क करें।','आधार, बैंक खाता और जॉब कार्ड की जानकारी दें।','पोर्टल पर स्वीकृति और किस्तों की स्थिति देखें।'],
'https://pmayg.nic.in/', 'https://pmayg.nic.in/', 'Ministry of Rural Development', '2026-09-12', 'verified'),

('atal-pension-yojana', 'Atal Pension Yojana', 'अटल पेंशन योजना',
'Guaranteed pension after 60 for workers in the unorganised sector.',
'असंगठित क्षेत्र के कामगारों को 60 वर्ष के बाद निश्चित पेंशन।',
'Atal Pension Yojana is a government-backed pension scheme mainly for workers in the unorganised sector. Subscribers contribute monthly until the age of 60 and then receive a guaranteed monthly pension as per the chosen slab.',
'अटल पेंशन योजना मुख्य रूप से असंगठित क्षेत्र के कामगारों के लिए सरकार समर्थित पेंशन योजना है। ग्राहक 60 वर्ष की उम्र तक हर महीने अंशदान करते हैं और उसके बाद चुने गए स्लैब के अनुसार निश्चित मासिक पेंशन पाते हैं।',
'social-support', 'Ministry of Finance, Pension Fund Regulatory and Development Authority', 'वित्त मंत्रालय, पेंशन निधि विनियामक एवं विकास प्राधिकरण',
ARRAY['Guaranteed monthly pension after the age of 60','Pension continues to the spouse after the subscriber','Contribution auto-debited from the savings bank account'],
ARRAY['60 वर्ष के बाद निश्चित मासिक पेंशन','ग्राहक के बाद जीवनसाथी को पेंशन','बचत बैंक खाते से अंशदान स्वतः कटता है'],
18, 40, NULL, '{}', '{}', '{}', NULL, NULL,
'[{"key":"bank","en":"You must have a savings bank or post office savings account.","hi":"आपके पास बचत बैंक या डाकघर बचत खाता होना चाहिए।"},{"key":"income-tax","en":"Income tax payers are not eligible to join, as notified.","hi":"अधिसूचना के अनुसार आयकर देने वाले शामिल नहीं हो सकते।"}]'::jsonb,
ARRAY['Read the scheme details on the official PFRDA/NPS Trust page.','Visit your bank branch or use your bank''s net banking Atal Pension Yojana option.','Choose your pension slab and fill the subscriber form.','Give consent for monthly auto-debit from your account.','Keep the PRAN acknowledgement for your records.'],
ARRAY['आधिकारिक पीएफआरडीए/एनपीएस ट्रस्ट पेज पर योजना की जानकारी पढ़ें।','अपनी बैंक शाखा जाएँ या नेट बैंकिंग में अटल पेंशन योजना विकल्प चुनें।','पेंशन स्लैब चुनें और ग्राहक फ़ॉर्म भरें।','खाते से हर महीने ऑटो-डेबिट की सहमति दें।','पीआरएएन रसीद संभाल कर रखें।'],
'https://npscra.nsdl.co.in/scheme-details.php', NULL, 'PFRDA / NPS Trust', '2026-09-12', 'source_only'),

('pm-mudra-yojana', 'Pradhan Mantri MUDRA Yojana', 'प्रधानमंत्री मुद्रा योजना',
'Collateral-free loans for small non-farm businesses.',
'छोटे गैर-कृषि कारोबार के लिए बिना गारंटी ऋण।',
'Pradhan Mantri MUDRA Yojana provides collateral-free loans through banks, non-banking finance companies and micro finance institutions to small non-farm income generating activities, under the Shishu, Kishore and Tarun categories.',
'प्रधानमंत्री मुद्रा योजना बैंकों, एनबीएफसी और सूक्ष्म वित्त संस्थानों के ज़रिये छोटे गैर-कृषि कामकाज के लिए शिशु, किशोर और तरुण श्रेणियों में बिना गारंटी ऋण देती है।',
'employment', 'Ministry of Finance, MUDRA Ltd.', 'वित्त मंत्रालय, मुद्रा लिमिटेड',
ARRAY['Collateral-free business loan in three categories','Available through banks, NBFCs and micro finance institutions','Can be used for working capital or business assets'],
ARRAY['तीन श्रेणियों में बिना गारंटी कारोबारी ऋण','बैंक, एनबीएफसी और सूक्ष्म वित्त संस्थानों से उपलब्ध','कार्यशील पूँजी या कारोबारी सामान के लिए उपयोग'],
18, NULL, NULL, '{}', ARRAY['self-employed','street-vendor','unemployed','other'], '{}', NULL, NULL,
'[{"key":"activity","en":"The loan must be for a non-farm income generating activity such as manufacturing, trading, services or allied agriculture activities as notified.","hi":"ऋण गैर-कृषि आय गतिविधि जैसे निर्माण, व्यापार, सेवा या अधिसूचित सहायक कृषि कार्य के लिए होना चाहिए।"},{"key":"lender","en":"Final sanction is decided by the lending bank or institution after its own appraisal.","hi":"अंतिम स्वीकृति ऋण देने वाला बैंक या संस्था अपनी जाँच के बाद तय करती है।"}]'::jsonb,
ARRAY['Read the loan categories on the official MUDRA website.','Prepare a simple business plan and cost estimate.','Approach a bank, NBFC or micro finance institution of your choice.','Submit the loan application with your KYC and business documents.','Follow up with the lender for sanction and disbursement.'],
ARRAY['आधिकारिक मुद्रा वेबसाइट पर ऋण श्रेणियाँ पढ़ें।','सरल कारोबारी योजना और लागत का अनुमान तैयार करें।','अपनी पसंद के बैंक, एनबीएफसी या सूक्ष्म वित्त संस्थान से संपर्क करें।','केवाईसी और कारोबारी दस्तावेज़ों के साथ ऋण आवेदन जमा करें।','स्वीकृति और भुगतान के लिए संस्था से संपर्क में रहें।'],
'https://www.mudra.org.in/', 'https://www.mudra.org.in/', 'MUDRA Ltd., Government of India', '2026-09-12', 'verified');

-- Required documents per scheme
INSERT INTO public.scheme_documents (scheme_id, doc_key, name_en, name_hi, instructions_en, instructions_hi, sort_order)
SELECT s.id, d.doc_key, d.name_en, d.name_hi, d.instructions_en, d.instructions_hi, d.sort_order
FROM public.schemes s
JOIN (VALUES
  ('pm-kisan','aadhaar','Aadhaar card','आधार कार्ड','Your own Aadhaar card. Make sure your name matches the land record.','अपना आधार कार्ड। नाम ज़मीन के रिकॉर्ड से मिलता हो।',1),
  ('pm-kisan','land-record','Land record document','ज़मीन का रिकॉर्ड','Khatauni, khasra or record of rights showing land in your name.','खतौनी, खसरा या अधिकार अभिलेख जिसमें ज़मीन आपके नाम हो।',2),
  ('pm-kisan','bank-proof','Bank account proof','बैंक खाते का प्रमाण','Passbook first page or cancelled cheque with IFSC code.','पासबुक का पहला पेज या आईएफएससी कोड वाला रद्द चेक।',3),
  ('ayushman-bharat-pmjay','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar of the family member seeking treatment.','इलाज कराने वाले सदस्य का आधार।',1),
  ('ayushman-bharat-pmjay','ration-card','Ration card or family ID','राशन कार्ड या परिवार पहचान','Used to confirm family members during verification.','सत्यापन के समय परिवार के सदस्यों की पुष्टि के लिए।',2),
  ('central-sector-scholarship','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar of the student.','छात्र का आधार कार्ड।',1),
  ('central-sector-scholarship','marksheet','Class 12 marksheet','कक्षा 12 की मार्कशीट','Board marksheet showing your percentage.','बोर्ड की मार्कशीट जिसमें प्रतिशत दिखे।',2),
  ('central-sector-scholarship','income-certificate','Income certificate','आय प्रमाण पत्र','Family income certificate from the competent authority.','सक्षम अधिकारी द्वारा जारी परिवार का आय प्रमाण पत्र।',3),
  ('central-sector-scholarship','bank-proof','Bank account proof','बैंक खाते का प्रमाण','Passbook in the student''s own name.','छात्र के अपने नाम की पासबुक।',4),
  ('central-sector-scholarship','admission-proof','Proof of admission','प्रवेश का प्रमाण','Fee receipt or bonafide certificate from the college.','कॉलेज की फ़ीस रसीद या बोनाफ़ाइड सर्टिफिकेट।',5),
  ('pm-svanidhi','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar linked with your mobile number.','मोबाइल नंबर से जुड़ा आधार कार्ड।',1),
  ('pm-svanidhi','vending-certificate','Certificate of vending or letter of recommendation','वेंडिंग सर्टिफिकेट या सिफ़ारिश पत्र','Issued by your urban local body.','आपके शहरी निकाय द्वारा जारी।',2),
  ('pm-svanidhi','bank-proof','Bank account proof','बैंक खाते का प्रमाण','Savings account passbook.','बचत खाते की पासबुक।',3),
  ('pmuy','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar of the woman applicant.','महिला आवेदक का आधार कार्ड।',1),
  ('pmuy','address-proof','Address proof','पते का प्रमाण','Any accepted proof of your current address.','आपके वर्तमान पते का मान्य प्रमाण।',2),
  ('pmuy','bank-proof','Bank account proof','बैंक खाते का प्रमाण','Passbook of the applicant''s bank account.','आवेदक के बैंक खाते की पासबुक।',3),
  ('sukanya-samriddhi','birth-certificate','Birth certificate of the girl child','बालिका का जन्म प्रमाण पत्र','Issued by the municipal authority or hospital.','नगर निकाय या अस्पताल द्वारा जारी।',1),
  ('sukanya-samriddhi','guardian-id','Guardian identity and address proof','अभिभावक का पहचान व पते का प्रमाण','Aadhaar or other KYC document of the guardian.','अभिभावक का आधार या अन्य केवाईसी दस्तावेज़।',2),
  ('pmay-gramin','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar of the head of the household.','परिवार के मुखिया का आधार कार्ड।',1),
  ('pmay-gramin','bank-proof','Bank account proof','बैंक खाते का प्रमाण','Passbook with account number and IFSC.','खाता नंबर और आईएफएससी वाली पासबुक।',2),
  ('pmay-gramin','job-card','MGNREGS job card','मनरेगा जॉब कार्ड','If your household has one.','यदि आपके परिवार के पास है।',3),
  ('atal-pension-yojana','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar of the subscriber.','ग्राहक का आधार कार्ड।',1),
  ('atal-pension-yojana','bank-proof','Savings bank account proof','बचत बैंक खाते का प्रमाण','Account from which the contribution will be auto-debited.','वह खाता जिससे अंशदान कटेगा।',2),
  ('pm-mudra-yojana','aadhaar','Aadhaar card','आधार कार्ड','Aadhaar of the applicant.','आवेदक का आधार कार्ड।',1),
  ('pm-mudra-yojana','business-plan','Business plan or cost estimate','कारोबारी योजना या लागत अनुमान','A simple written plan of your business and costs.','आपके कारोबार और लागत की सरल लिखित योजना।',2),
  ('pm-mudra-yojana','bank-proof','Bank account proof','बैंक खाते का प्रमाण','Passbook or statement of your account.','आपके खाते की पासबुक या स्टेटमेंट।',3)
) AS d(slug, doc_key, name_en, name_hi, instructions_en, instructions_hi, sort_order)
ON d.slug = s.slug;
